package connect.four.web.entity;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "NeuralNetworks")
public class NeuralNetwork {

	@Id
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	private String definition;

	public String getDefinition() {
		return definition;
	}

	public String getId() {
		return id;
	}

	public void setDefinition(String definition) {
		this.definition = definition;
	}

	public void setId(String id) {
		this.id = id;
	}
}
